### ISSUE TITLE
IOS上和微信支付插件冲突了，怎么解决冲突？

### ISSUE THREAD

**Issue by jethroHuang** [MobClub/ShareSDK-For-Flutter#11]
同时集成了 sharesdk 和 fluwx(微信支付插件)，结果他们都有libwechatsdk.a。。。然后运行flutter run 就会报

target has libraries with conflicting names libwechatsdk.a

我在网上找到的解决方案是删除 libwechatsdk.a 文件，但是运行后又会报错提示没找到 libwechatsdk.a 

请问该如何解决这个冲突？

**Comment by DangerousDON** [comment]
您可以只保留一个微信sdk就行，留下我们sdk里下载的待支付的微信sdk，把其他第三方里的微信sdk删除掉就行
把我们的这个微信命令换成带支付的微信sdk命令
s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'



刘芳丽
MOB云事业部 技术支持 
YOOZOO GAMES 游族网络

E • liufl@yoozoo.com
M • +86 18824179331
T • +86 21 3367 6512
F • +86 21 3367 6520

YOOZOO MANSION,BUILDING 2,711 YISHAN RD.,XUHUI DISTRICT,SHANGHAI,CHINA 上海市徐汇区宜山路711号2号楼游族大厦 2200233




本邮件可能载有机密内容，非指定收件人请勿打开、复制本邮件或依赖本邮件的内容而采取任何行动。若误收到本邮件，请立即通知发送人，并删除本邮件及其附件。谢谢！
This message contains information which may be confidential and privileged. If you received the message by mistake, please inform the sender and delete the message as soon as possible, thanks.

 
发件人： jethroHuang
发送时间： 2019-04-03 17:16
收件人： MobClub/ShareSDK-For-Flutter
抄送： Subscribed
主题： [MobClub/ShareSDK-For-Flutter] IOS上和微信支付插件冲突了，怎么解决冲突？ (#11)
同时集成了 sharesdk 和 fluwx(微信支付插件)，结果他们都有libwechatsdk.a。。。然后运行flutter run 就会报
target has libraries with conflicting names libwechatsdk.a
我在网上找到的解决方案是删除 libwechatsdk.a 文件，但是运行后又会报错提示没找到 libwechatsdk.a
请问该如何解决这个冲突？

**Comment by jethroHuang** [comment]
> 您可以只保留一个微信sdk就行，留下我们sdk里下载的待支付的微信sdk，把其他第三方里的微信sdk删除掉就行 把我们的这个微信命令换成带支付的微信sdk命令 s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull' 刘芳丽 MOB云事业部 技术支持 YOOZOO GAMES 游族网络 E • liufl@yoozoo.com M • +86 18824179331 T • +86 21 3367 6512 F • +86 21 3367 6520 YOOZOO MANSION,BUILDING 2,711 YISHAN RD.,XUHUI DISTRICT,SHANGHAI,CHINA 上海市徐汇区宜山路711号2号楼游族大厦 2200233 本邮件可能载有机密内容，非指定收件人请勿打开、复制本邮件或依赖本邮件的内容而采取任何行动。若误收到本邮件，请立即通知发送人，并删除本邮件及其附件。谢谢！ This message contains information which may be confidential and privileged. If you received the message by mistake, please inform the sender and delete the message as soon as possible, thanks. 发件人： jethroHuang 发送时间： 2019-04-03 17:16 收件人： MobClub/ShareSDK-For-Flutter 抄送： Subscribed 主题： [MobClub/ShareSDK-For-Flutter] IOS上和微信支付插件冲突了，怎么解决冲突？ (#11) 同时集成了 sharesdk 和 fluwx(微信支付插件)，结果他们都有libwechatsdk.a。。。然后运行flutter run 就会报 target has libraries with conflicting names libwechatsdk.a 我在网上找到的解决方案是删除 libwechatsdk.a 文件，但是运行后又会报错提示没找到 libwechatsdk.a 请问该如何解决这个冲突？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

您说的这个命令是在哪个文件中？

**Comment by DangerousDON** [comment]
sharesdk.podspec 文件，您可以看下我们的文档说明http://wiki.mob.com/sharesdk-for-flutter/，，，我们默认里面是不带支付的微信sdk，您要做支付的话，就用我们带支付的微信sdk命令就行，重新编辑下 sharesdk.podspec 文件设置 dependency



刘芳丽
MOB云事业部 技术支持 
YOOZOO GAMES 游族网络

E • liufl@yoozoo.com
M • +86 18824179331
T • +86 21 3367 6512
F • +86 21 3367 6520

YOOZOO MANSION,BUILDING 2,711 YISHAN RD.,XUHUI DISTRICT,SHANGHAI,CHINA 上海市徐汇区宜山路711号2号楼游族大厦 2200233




本邮件可能载有机密内容，非指定收件人请勿打开、复制本邮件或依赖本邮件的内容而采取任何行动。若误收到本邮件，请立即通知发送人，并删除本邮件及其附件。谢谢！
This message contains information which may be confidential and privileged. If you received the message by mistake, please inform the sender and delete the message as soon as possible, thanks.

 
发件人： jethroHuang
发送时间： 2019-04-03 17:29
收件人： MobClub/ShareSDK-For-Flutter
抄送： Donel Chan; Comment
主题： Re: [MobClub/ShareSDK-For-Flutter] IOS上和微信支付插件冲突了，怎么解决冲突？ (#11)
您可以只保留一个微信sdk就行，留下我们sdk里下载的待支付的微信sdk，把其他第三方里的微信sdk删除掉就行 把我们的这个微信命令换成带支付的微信sdk命令 s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull' 刘芳丽 MOB云事业部 技术支持 YOOZOO GAMES 游族网络 E • liufl@yoozoo.com M • +86 18824179331 T • +86 21 3367 6512 F • +86 21 3367 6520 YOOZOO MANSION,BUILDING 2,711 YISHAN RD.,XUHUI DISTRICT,SHANGHAI,CHINA 上海市徐汇区宜山路711号2号楼游族大厦 2200233 本邮件可能载有机密内容，非指定收件人请勿打开、复制本邮件或依赖本邮件的内容而采取任何行动。若误收到本邮件，请立即通知发送人，并删除本邮件及其附件。谢谢！ This message contains information which may be confidential and privileged. If you received the message by mistake, please inform the sender and delete the message as soon as possible, thanks. 发件人： jethroHuang 发送时间： 2019-04-03 17:16 收件人： MobClub/ShareSDK-For-Flutter 抄送： Subscribed 主题： [MobClub/ShareSDK-For-Flutter] IOS上和微信支付插件冲突了，怎么解决冲突？ (#11) 同时集成了 sharesdk 和 fluwx(微信支付插件)，结果他们都有libwechatsdk.a。。。然后运行flutter run 就会报 target has libraries with conflicting names libwechatsdk.a 我在网上找到的解决方案是删除 libwechatsdk.a 文件，但是运行后又会报错提示没找到 libwechatsdk.a 请问该如何解决这个冲突？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
您说的这个命令是在哪个文件中？

**Comment by CyJaySong** [comment]
sharesdk的完整版微信SDK里包装了share的桥接文件下载，删了是做不了分享的，删了fluwx中微信SDK的libwechatsdk.a。然后在fluwx的podspec里添加 s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'。这样做可以解决冲突

**Comment by GanZhiXiong** [comment]
我通过这里解决了，你们也可以试试看
https://github.com/OpenFlutter/fluwx/blob/master/doc/QUESTIONS_CN.md#sharesdk%E5%88%86%E4%BA%AB%E6%8F%92%E4%BB%B6%E5%92%8Cfluwx%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98%E6%8F%92%E4%BB%B6%E5%AD%98%E5%9C%A8%E5%86%B2%E7%AA%81

**Comment by Lanhaoo** [comment]
> sharesdk的完整版微信SDK里包装了share的桥接文件下载，删了是做不了分享的，删了fluwx中微信SDK的libwechatsdk.a。然后在fluwx的podspec里添加 s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'。这样做可以解决冲突

我按照这种方式还是没有解决。我先添加了fluwx，然后删了fluwx中微信SDK的libwechatsdk.a，然后在fluwx的podspec里添加 s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'，最后添加sharesdk并且把sharesdk的podspec中的s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChat' 修改成了s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'。结果还是报错

**Comment by waymon1023** [comment]
> > sharesdk的完整版微信SDK里包装了share的桥接文件下载，删了是做不了分享的，删了fluwx中微信SDK的libwechatsdk.a。然后在fluwx的podspec里添加 s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'。这样做可以解决冲突
> 
> 我按照这种方式还是没有解决。我先添加了fluwx，然后删了fluwx中微信SDK的libwechatsdk.a，然后在fluwx的podspec里添加 s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'，最后添加sharesdk并且把sharesdk的podspec中的s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChat' 修改成了s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'。结果还是报错

老哥，现在你解决了吗

**Comment by waymon1023** [comment]
> > 您可以只保留一个微信sdk就行，留下我们sdk里下载的待支付的微信sdk，把其他第三方里的微信sdk删除掉就行 把我们的这个微信命令换成带支付的微信sdk命令 s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull' 刘芳丽 MOB云事业部 技术支持 YOOZOO GAMES 游族网络 E • [liufl@yoozoo.com](mailto:liufl@yoozoo.com) M • +86 18824179331 T • +86 21 3367 6512 F • +86 21 3367 6520 YOOZOO MANSION,BUILDING 2,711 YISHAN RD.,XUHUI DISTRICT,SHANGHAI,CHINA 上海市徐汇区宜山路711号2号楼游族大厦 2200233 本邮件可能载有机密内容，非指定收件人请勿打开、复制本邮件或依赖本邮件的内容而采取任何行动。若误收到本邮件，请立即通知发送人，并删除本邮件及其附件。谢谢！ This message contains information which may be confidential and privileged. If you received the message by mistake, please inform the sender and delete the message as soon as possible, thanks. 发件人： jethroHuang 发送时间： 2019-04-03 17:16 收件人： MobClub/ShareSDK-For-Flutter 抄送： Subscribed 主题： [MobClub/ShareSDK-For-Flutter] IOS上和微信支付插件冲突了，怎么解决冲突？ (#11) 同时集成了 sharesdk 和 fluwx(微信支付插件)，结果他们都有libwechatsdk.a。。。然后运行flutter run 就会报 target has libraries with conflicting names libwechatsdk.a 我在网上找到的解决方案是删除 libwechatsdk.a 文件，但是运行后又会报错提示没找到 libwechatsdk.a 请问该如何解决这个冲突？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 您说的这个命令是在哪个文件中？

同

> 同时集成了 sharesdk 和 fluwx(微信支付插件)，结果他们都有libwechatsdk.a。。。然后运行flutter run 就会报
> 
> target has libraries with conflicting names libwechatsdk.a
> 
> 我在网上找到的解决方案是删除 libwechatsdk.a 文件，但是运行后又会报错提示没找到 libwechatsdk.a
> 
> 请问该如何解决这个冲突？

老哥我现在和你一样，你解决了吗？

**Comment by DangerousDON** [comment]
第一在fluwx.podspec中将WechatOpenSDK去掉，修改sharesdk_plugin.podspec文件里面的微信命令为s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull

第二fluwx不动，引入我们的精简版，把微信命令换成s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChat_Lite'

有冲突那个应该是有多个微信sdk了，一个项目里只能有一个微信sdk，所以这2个插件，只能其中一个插件里导入微信sdk，其他的里面要删除掉



刘芳丽  Lisa Liu
基础技术平台  技术支持

E    • liufl@yoozoo.com
M   • 18824179331

FLOOR 4,SOUTH BUILDING B3,PUTIAN INFORMATION INDUSTRIAL PARK,700 YISHAN RD,XUHUI DISTRICT,SHANGHAI,CHINA
上海市徐汇区宜山路700号普天信息产业园B3南栋4层


本邮件可能载有机密内容，非指定收件人请勿打开、复制本邮件或依赖本邮件的内容而采取任何行动。若误收到本邮件，请立即通知发送人，并删除本邮件及其附件。谢谢！
This message contains information which may be confidential and privileged. If you received the message by mistake, please inform the sender and delete the message as soon as possible, thanks.

 
发件人： waymon1023
发送时间： 2020-11-05 20:41
收件人： MobClub/ShareSDK-For-Flutter
抄送： Donel Chan; Comment
主题： Re: [MobClub/ShareSDK-For-Flutter] IOS上和微信支付插件冲突了，怎么解决冲突？ (#11)
sharesdk的完整版微信SDK里包装了share的桥接文件下载，删了是做不了分享的，删了fluwx中微信SDK的libwechatsdk.a。然后在fluwx的podspec里添加 s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'。这样做可以解决冲突
我按照这种方式还是没有解决。我先添加了fluwx，然后删了fluwx中微信SDK的libwechatsdk.a，然后在fluwx的podspec里添加 s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'，最后添加sharesdk并且把sharesdk的podspec中的s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChat' 修改成了s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'。结果还是报错
老哥，现在你解决了吗

**Comment by DangerousDON** [comment]
第一在fluwx.podspec中将WechatOpenSDK去掉，修改sharesdk_plugin.podspec文件里面的微信命令为s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull

第二fluwx不动，引入我们的精简版，把微信命令换成s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChat_Lite'

有冲突那个应该是有多个微信sdk了，一个项目里只能有一个微信sdk，所以这2个插件，只能其中一个插件里导入微信sdk，其他的里面要删除掉


刘芳丽  Lisa Liu
基础技术平台  技术支持

E    • liufl@yoozoo.com
M   • 18824179331

FLOOR 4,SOUTH BUILDING B3,PUTIAN INFORMATION INDUSTRIAL PARK,700 YISHAN RD,XUHUI DISTRICT,SHANGHAI,CHINA
上海市徐汇区宜山路700号普天信息产业园B3南栋4层


本邮件可能载有机密内容，非指定收件人请勿打开、复制本邮件或依赖本邮件的内容而采取任何行动。若误收到本邮件，请立即通知发送人，并删除本邮件及其附件。谢谢！
This message contains information which may be confidential and privileged. If you received the message by mistake, please inform the sender and delete the message as soon as possible, thanks.

 
发件人： waymon1023
发送时间： 2020-11-05 20:41
收件人： MobClub/ShareSDK-For-Flutter
抄送： Donel Chan; Comment
主题： Re: [MobClub/ShareSDK-For-Flutter] IOS上和微信支付插件冲突了，怎么解决冲突？ (#11)
您可以只保留一个微信sdk就行，留下我们sdk里下载的待支付的微信sdk，把其他第三方里的微信sdk删除掉就行 把我们的这个微信命令换成带支付的微信sdk命令 s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull' 刘芳丽 MOB云事业部 技术支持 YOOZOO GAMES 游族网络 E • liufl@yoozoo.com M • +86 18824179331 T • +86 21 3367 6512 F • +86 21 3367 6520 YOOZOO MANSION,BUILDING 2,711 YISHAN RD.,XUHUI DISTRICT,SHANGHAI,CHINA 上海市徐汇区宜山路711号2号楼游族大厦 2200233 本邮件可能载有机密内容，非指定收件人请勿打开、复制本邮件或依赖本邮件的内容而采取任何行动。若误收到本邮件，请立即通知发送人，并删除本邮件及其附件。谢谢！ This message contains information which may be confidential and privileged. If you received the message by mistake, please inform the sender and delete the message as soon as possible, thanks. 发件人： jethroHuang 发送时间： 2019-04-03 17:16 收件人： MobClub/ShareSDK-For-Flutter 抄送： Subscribed 主题： [MobClub/ShareSDK-For-Flutter] IOS上和微信支付插件冲突了，怎么解决冲突？ (#11) 同时集成了 sharesdk 和 fluwx(微信支付插件)，结果他们都有libwechatsdk.a。。。然后运行flutter run 就会报 target has libraries with conflicting names libwechatsdk.a 我在网上找到的解决方案是删除 libwechatsdk.a 文件，但是运行后又会报错提示没找到 libwechatsdk.a 请问该如何解决这个冲突？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
您说的这个命令是在哪个文件中？
同
同时集成了 sharesdk 和 fluwx(微信支付插件)，结果他们都有libwechatsdk.a。。。然后运行flutter run 就会报
target has libraries with conflicting names libwechatsdk.a
我在网上找到的解决方案是删除 libwechatsdk.a 文件，但是运行后又会报错提示没找到 libwechatsdk.a
请问该如何解决这个冲突？
老哥我现在和你一样，你解决了吗？

**Comment by jethroHuang** [comment]
> 第一在fluwx.podspec中将WechatOpenSDK去掉，修改sharesdk_plugin.podspec文件里面的微信命令为s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull 第二fluwx不动，引入我们的精简版，把微信命令换成s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChat_Lite' 有冲突那个应该是有多个微信sdk了，一个项目里只能有一个微信sdk，所以这2个插件，只能其中一个插件里导入微信sdk，其他的里面要删除掉 刘芳丽 Lisa Liu 基础技术平台 技术支持 E • liufl@yoozoo.com M • 18824179331 FLOOR 4,SOUTH BUILDING B3,PUTIAN INFORMATION INDUSTRIAL PARK,700 YISHAN RD,XUHUI DISTRICT,SHANGHAI,CHINA 上海市徐汇区宜山路700号普天信息产业园B3南栋4层 本邮件可能载有机密内容，非指定收件人请勿打开、复制本邮件或依赖本邮件的内容而采取任何行动。若误收到本邮件，请立即通知发送人，并删除本邮件及其附件。谢谢！ This message contains information which may be confidential and privileged. If you received the message by mistake, please inform the sender and delete the message as soon as possible, thanks. 发件人： waymon1023 发送时间： 2020-11-05 20:41 收件人： MobClub/ShareSDK-For-Flutter 抄送： Donel Chan; Comment 主题： Re: [MobClub/ShareSDK-For-Flutter] IOS上和微信支付插件冲突了，怎么解决冲突？ (#11) 您可以只保留一个微信sdk就行，留下我们sdk里下载的待支付的微信sdk，把其他第三方里的微信sdk删除掉就行 把我们的这个微信命令换成带支付的微信sdk命令 s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChatFull' 刘芳丽 MOB云事业部 技术支持 YOOZOO GAMES 游族网络 E • liufl@yoozoo.com M • +86 18824179331 T • +86 21 3367 6512 F • +86 21 3367 6520 YOOZOO MANSION,BUILDING 2,711 YISHAN RD.,XUHUI DISTRICT,SHANGHAI,CHINA 上海市徐汇区宜山路711号2号楼游族大厦 2200233 本邮件可能载有机密内容，非指定收件人请勿打开、复制本邮件或依赖本邮件的内容而采取任何行动。若误收到本邮件，请立即通知发送人，并删除本邮件及其附件。谢谢！ This message contains information which may be confidential and privileged. If you received the message by mistake, please inform the sender and delete the message as soon as possible, thanks. 发件人： jethroHuang 发送时间： 2019-04-03 17:16 收件人： MobClub/ShareSDK-For-Flutter 抄送： Subscribed 主题： [MobClub/ShareSDK-For-Flutter] IOS上和微信支付插件冲突了，怎么解决冲突？ (#11) 同时集成了 sharesdk 和 fluwx(微信支付插件)，结果他们都有libwechatsdk.a。。。然后运行flutter run 就会报 target has libraries with conflicting names libwechatsdk.a 我在网上找到的解决方案是删除 libwechatsdk.a 文件，但是运行后又会报错提示没找到 libwechatsdk.a 请问该如何解决这个冲突？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. 您说的这个命令是在哪个文件中？ 同 同时集成了 sharesdk 和 fluwx(微信支付插件)，结果他们都有libwechatsdk.a。。。然后运行flutter run 就会报 target has libraries with conflicting names libwechatsdk.a 我在网上找到的解决方案是删除 libwechatsdk.a 文件，但是运行后又会报错提示没找到 libwechatsdk.a 请问该如何解决这个冲突？ 老哥我现在和你一样，你解决了吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

使用第二个方案成功编译了

**Comment by jethroHuang** [comment]
> fluwx不动，引入ShareSDK的精简版，把微信命令换成s.dependency 'mob_sharesdk/ShareSDKPlatforms/WeChat_Lite'

此方案可解决冲突
